CPPFLAGS = -O2 -g -std=c++11 -Wall

all: hw3_1 hw3_2

hw3_1: hw3_1.cpp
	g++ $(CPPFLAGS) hw3_1.cpp -o 3_4_1.out
hw3_2: hw3_2.cpp
	g++ $(CPPFLAGS) hw3_2.cpp -o 3_4_2.out
run1:
	./3_4_1.out
run2:
	./3_4_2.out
